### ISSUE TITLE
Support for variable height

### ISSUE THREAD

**Issue by bobvanderlinden** [sgomes/css-aspect-ratio#2]
I have a div that has an fixed aspect ratio. I'd like to fit that div inside its parent while maintaining the aspect ratio. Currently this works with this library when the aspect ratio of the parent is smaller than the aspect ratio of its child. However, whenever this is not the case (the parent is wider than its child) the height of the child becomes larger than its parent.

An example: https://jsfiddle.net/5pz0w2jc/

You'll see that when the parent is less wider than its child then things are alright. However when the parent is wider than its child the child is incorrectly sized.

I've been thinking of a way to fix this, but it probably requires the aspect ratio of the parent to be available in css during calc.

**Comment by sgomes** [comment]
Hello there!

My gut feeling is that it is not possible to do this in a way that's generic enough for both height and width, and works with any element. As you mention, you'd need access to the height somehow.

The padding trick used here works because `padding-top` is relative to the container's width. Unfortunately, the reverse is not true; `padding-left` is also relative to the container's width, not its height. We'd therefore need a different trick for this to work with height constraints.

CSS is a big and complex beast, so I'm not definitively saying there's no way to do this in a way that's generic enough for both height and width, and works with any element. That said, as of right now, I don't know any way of achieving that :-/

However, if your use case is images or video and you have a fixed height container, consider using [`object-fit: contain` or `object-fit: scale-down`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit). Since the height is fixed, you won't get the content shift that this module is trying to avoid, and `object-fit` takes care of maintaining the aspect ratio. [The support matrix for the feature](http://caniuse.com/#feat=object-fit) is pretty good, too.

Hope this helps!

**Comment by bobvanderlinden** [comment]
Thanks for your reaction. I was afraid it wouldn't be possible with pure CSS. Like you said, it's a complex beast... too bad it sometimes is still very restraining.

My use-case was for maintaining an aspect ratio for an HTML element and not just images (like a board of tic-tac-toe or a dynamic svg). That said <canvas> also seems to be able to use `object-fit` on most browsers.

I currently solved the issue using a custom React component and `react-resize-detector`. So if anyone still needs to solve this have a look [here](https://gist.github.com/bobvanderlinden/8422f92730afb8d6c29d635c6330ba53).
